version: '3.7'

services:
  backend-core:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: backend-core
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev