version: '3.7'

services:
  backend-core:
    container_name: backend-core
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - mongodb
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npm run dev
volumes:
  db: